const products = [
    {
        id: 1,
        title: "Cafe Negro",
        stock: 10,
        photo: "./assets/images/CafeNegro.png",
        price: 250,
        categoria: "capsulas",
    },
    {
        id: 2,
        title: "Cafe Azul",
        stock: 10,
        photo: "./assets/images/CafeAzul.png",
        price: 180,
    },
    {
        id: 3,
        title: "Cafe Rojo",
        stock: 10,
        photo: "./assets/images/CafeRojo.png",
        price: 180,
        categoria: "capsulas",
    },
    {
        id: 4,
        title: "Cafe Verde",
        stock: 10,
        photo: "./assets/images/CafeVerde.png",
        price: 180,
        categoria: "capsulas",
    },
    {
        id: 5,
        title: "Cafe Naranja",
        stock: 10,
        photo: "./assets/images/CafeNaranja.png",
        price: 200,
        categoria: "capsulas",
    },
    {
        id: 6,
        title: "Cafe Dorado",
        stock: 10,
        photo: "./assets/images/CafeDorado.png",
        price: 350,
        categoria: "capsulas",
    },
    {
        id: 7,
        title: "Cafe Rosa",
        stock: 10,
        photo: "../assets/images/CafeRosa.png",
        price: 200,
        categoria: "capsulas",
    },
    {
        id: 8,
        title: "Cafe Marron",
        stock: 10,
        photo: "./assets/images/CafeMarron.png",
        price: 100,
        categoria: "capsulas",
    },
    {
        id: 9,
        title: "Cafe Blanco",
        stock: 10,
        photo: "./assets/images/CafeBlanco.png",
        price: 250,
        categoria: "capsulas",
    },
    {
        id: 10,
        title: "Cafe Violeta",
        stock: 10,
        photo: "./assets/images/CafeVioleta.png",
        price: 200,
        categoria: "capsulas",
    },
    {
        id: 11,
        title: "Cafetera Doble Red",
        stock: 10,
        photo: "./assets/images/cafetera.png",
        price: 4500,
        categoria: "cafeteras",
    },
    {
        id: 12,
        title: "Cafetera Basic",
        stock: 10,
        photo: "./assets/images/cafetera2.png",
        price: 1500,
        categoria: "cafeteras",
    },
    {
        id: 13,
        title: "Cafetera Simple",
        stock: 10,
        photo: "./assets/images/cafetera3.png",
        price: 1000,
        categoria: "cafeteras",
    },
    {
        id: 14,
        title: "Cafetera Black Expresso",
        stock: 10,
        photo: "./assets/images/cafetera4.png",
        price: 2500,
        categoria: "cafeteras",
    },
    {
        id: 15,
        title: "Cafetera Metalica",
        stock: 10,
        photo: "./assets/images/cafetera5.png",
        price: 2800,
        categoria: "cafeteras",
    },
    {
        id: 16,
        title: "Cafetera Metal Red",
        stock: 10,
        photo: "./assets/images/cafetera6.png",
        price: 5000,
        categoria: "cafeteras",
    },
    {
        id: 17,
        title: "Cafetera Milk Red",
        stock: 10,
        photo: "./assets/images/cafetera7.png",
        price: 7000,
        categoria: "cafeteras",
    },
    {
        id: 18,
        title: "Cafetera Doble Black",
        stock: 10,
        photo: "./assets/images/cafetera8.jpg",
        price: 4000,
        categoria: "cafeteras",
    },
    {
        id: 19,
        title: "Filtro Simple",
        stock: 10,
        photo: "./assets/images/filtros2.png",
        price: 50,
        categoria: "filtros",
    },
    {
        id: 20,
        title: "Filtro Doble ",
        stock: 10,
        photo: "./assets/images/filtros3.png",
        price: 400,
        categoria: "filtros",
    },
    {
        id: 21,
        title: "Granos Negros Suaves",
        stock: 10,
        photo: "./assets/images/granos1.png",
        price: 700,
        categoria: "granos",
    },
    {
        id: 22,
        title: "Granos Veganos",
        stock: 10,
        photo: "./assets/images/granos2.png",
        price: 1400,
        categoria: "granos",
    },
    {
        id: 23,
        title: "Granos Stevia",
        stock: 10,
        photo: "./assets/images/granos3.png",
        price: 900,
        categoria: "granos",
    },
    {
        id: 24,
        title: "Granos Colombianos",
        stock: 10,
        photo: "./assets/images/granos4.png",
        price: 2400,
        categoria: "granos",
    },
    {
        id: 25,
        title: "Granos Extra Suaves",
        stock: 10,
        photo: "./assets/images/granos5.png",
        price: 1000,
        categoria: "granos",
    },
    {
        id: 26,
        title: "Granos Vegetarianos",
        stock: 10,
        photo: "./assets/images/granos6.png",
        price: 1800,
        categoria: "granos",
    },
    {
        id: 27,
        title: "Granos Latte",
        stock: 10,
        photo: "./assets/images/granos7.png",
        price: 650,
        categoria: "granos",
    },
    {
        id: 28,
        title: "Granos Nespresso",
        stock: 10,
        photo: "./assets/images/granos8.png",
        price: 3400,
        categoria: "granos",
    },
    {
        id: 29,
        title: "Granos Dolcata",
        stock: 10,
        photo: "./assets/images/granos9.png",
        price: 5400,
        categoria: "granos",
    },
    {
        id: 30,
        title: "Taza Infantil",
        stock: 10,
        photo: "./assets/images/taza.png",
        price: 1500,
        categoria: "tazas",
    },
    {
        id: 31,
        title: "Taza Red Con Base",
        stock: 10,
        photo: "./assets/images/taza2.png",
        price: 800,
        categoria: "tazas",
    },
    {
        id: 32,
        title: "Taza Mango Rojo Frases",
        stock: 10,
        photo: "./assets/images/taza3.png",
        price: 1500,
        categoria: "tazas",
    },
    {
        id: 33,
        title: "Taza Black Colour",
        stock: 10,
        photo: "./assets/images/taza4.png",
        price: 1100,
        categoria: "tazas",
    },
    {
        id: 34,
        title: "Taza Black Frase",
        stock: 10,
        photo: "./assets/images/taza5.png",
        price: 800,
        categoria: "tazas",
    },
    {
        id: 35,
        title: "Taza Vidrio Small",
        stock: 10,
        photo: "./assets/images/taza6.png",
        price: 1000,
        categoria: "tazas",
    },
    {
        id: 36,
        title: "Taza Red Small",
        stock: 10,
        photo: "./assets/images/taza7.png",
        price: 900,
        categoria: "tazas",
    },
    {
        id: 37,
        title: "Taza Con Base Galletas",
        stock: 10,
        photo: "./assets/images/taza8.png",
        price: 1900,
        categoria: "tazas",
    },
    {
        id: 38,
        title: "Taza Con Cuchara",
        stock: 10,
        photo: "./assets/images/taza9.png",
        price: 1500,
        categoria: "tazas",
    },
    {
        id: 39,
        title: "Taza Vidrio Medium",
        stock: 10,
        photo: "./assets/images/taza10.png",
        price: 1300,
        categoria: "tazas",
    },
    {
        id: 40,
        title: "Taza Vidrio Grande",
        stock: 10,
        photo: "./assets/images/taza11.png",
        price: 1300,
        categoria: "tazas",
    },
    {
        id: 41,
        title: "Taza Copa",
        stock: 10,
        photo: "./assets/images/taza12.png",
        price: 2000,
        categoria: "tazas",
    },
    {
        id: 42,
        title: "Taza Large XXL",
        stock: 10,
        photo: "./assets/images/taza13.png",
        price: 2500,
        categoria: "tazas",
    },
    {
        id: 43,
        title: "Taza Corazon Red",
        stock: 10,
        photo: "./assets/images/taza14.png",
        price: 2000,
        categoria: "tazas",
    },
    {
        id: 44,
        title: "Taza Vidrio Vaso",
        stock: 10,
        photo: "./assets/images/taza15.png",
        price: 1500,
        categoria: "tazas",
    },
    {
        id: 45,
        title: "Taza Universo",
        stock: 10,
        photo: "./assets/images/taza16.png",
        price: 1800,
        categoria: "tazas",
    },
    {
        id: 46,
        title: "Taza Con Tapa Termica",
        stock: 10,
        photo: "./assets/images/taza17.png",
        price: 1800,
        categoria: "tazas",
    },
    {
        id: 47,
        title: "Taza Basic Colour",
        stock: 10,
        photo: "./assets/images/taza18.png",
        price: 900,
        categoria: "tazas",
    },
    {
        id: 48,
        title: "Vaso Termico Red And Black",
        stock: 10,
        photo: "./assets/images/VasoTermico.png",
        price: 2900,
        categoria: "vasos",
    },
    {
        id: 49,
        title: "Vaso Termico Personalizado",
        stock: 10,
        photo: "./assets/images/VasoTermico2.png",
        price: 1900,
        categoria: "vasos",
    },
    {
        id: 50,
        title: "Vaso Termico Metalico",
        stock: 10,
        photo: "./assets/images/VasoTermico3.png",
        price: 2500,
        categoria: "vasos",
    },
    {
        id: 51,
        title: "Vaso Termico Basic Colour",
        stock: 10,
        photo: "./assets/images/VasoTermico5.png",
        price: 1400,
        categoria: "vasos",
    },
    {
        id: 52,
        title: "Vaso Termico Con Mango Color",
        stock: 10,
        photo: "./assets/images/VasoTermico5.png",
        price: 1700,
        categoria: "vasos",
    },
    {
        id: 53,
        title: "Vaso Termico Metalico Color",
        stock: 10,
        photo: "./assets/images/VasoTermico6.png",
        price: 2200,
        categoria: "vasos",
    },
    {
        id: 54,
        title: "Vaso Termico Small Personalizado",
        stock: 10,
        photo: "./assets/images/VasoTermico8.png",
        price: 1000,
        categoria: "vasos",
    },
    {
        id: 55,
        title: "Vaso Termico Stanley",
        stock: 10,
        photo: "./assets/images/VasoTermico4.png",
        price: 5900,
        categoria: "vasos",
    },
];

export const getFetch = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve(products);
    }, 2000);
});

const OneProduct = {
    id: 1,
    title: "Cafe Negro",
    stock: 10,
    photo: "./assets/images/CafeNegro.png",
    price: 250,
    desc: "Este café para aquellos que aman el café intenso y de moderada acidez.",
};

export const getFetchOneProduct = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve(OneProduct);
    }, 2000);
});
