// const products = [
//     {
//         id: 1,
//         title: "Cafe Negro",
//         stock: 10,
//         photo: "https://i.ibb.co/PDVq65D/Cafe-Negro.png",
//         price: 250,
//         categoria: "capsulas",
//     },
//     {
//         id: 2,
//         title: "Cafe Azul",
//         stock: 10,
//         photo: "https://i.ibb.co/F6F91sG/CafeAzul.png",
//         price: 180,
//     },
//     {
//         id: 3,
//         title: "Cafe Rojo",
//         stock: 10,
//         photo: "https://i.ibb.co/SB6LDhd/CafeRojo.png",
//         price: 180,
//         categoria: "capsulas",
//     },
//     {
//         id: 4,
//         title: "Cafe Verde",
//         stock: 10,
//         photo: "https://i.ibb.co/mFfMxQ8/Cafe-Verde.png",
//         price: 180,
//         categoria: "capsulas",
//     },
//     {
//         id: 5,
//         title: "Cafe Naranja",
//         stock: 10,
//         photo: "https://i.ibb.co/d5GX3d7/Cafe-Naranja.png",
//         price: 200,
//         categoria: "capsulas",
//     },
//     {
//         id: 6,
//         title: "Cafe Dorado",
//         stock: 10,
//         photo: "https://i.ibb.co/XZkLKQf/Cafe-Dorado.png",
//         price: 350,
//         categoria: "capsulas",
//     },
//     {
//         id: 7,
//         title: "Cafe Rosa",
//         stock: 10,
//         photo: "https://i.ibb.co/yf04Tj4/CafeRosa.png",
//         price: 200,
//         categoria: "capsulas",
//     },
//     {
//         id: 8,
//         title: "Cafe Marron",
//         stock: 10,
//         photo: "https://i.ibb.co/RCtnFND/Cafe-Marron.png",
//         price: 100,
//         categoria: "capsulas",
//     },
//     {
//         id: 9,
//         title: "Cafe Blanco",
//         stock: 10,
//         photo: "https://i.ibb.co/80G38Fg/Cafe-Blanco.png",
//         price: 250,
//         categoria: "capsulas",
//     },
//     {
//         id: 10,
//         title: "Cafe Violeta",
//         stock: 10,
//         photo: "https://i.ibb.co/rmyJ4jg/Cafe-Violeta.png",
//         price: 200,
//         categoria: "capsulas",
//     },
//     {
//         id: 11,
//         title: "Cafetera Doble Red",
//         stock: 10,
//         photo: "https://i.ibb.co/tmjSghV/cafetera.png",
//         price: 4500,
//         categoria: "cafeteras",
//     },
//     {
//         id: 12,
//         title: "Cafetera Basic",
//         stock: 10,
//         photo: "https://i.ibb.co/b3vnJYj/cafetera2.png",
//         price: 1500,
//         categoria: "cafeteras",
//     },
//     {
//         id: 13,
//         title: "Cafetera Simple",
//         stock: 10,
//         photo: "https://i.ibb.co/GRRnT2g/cafetera3.png",
//         price: 1000,
//         categoria: "cafeteras",
//     },
//     {
//         id: 14,
//         title: "Cafetera Black Expresso",
//         stock: 10,
//         photo: "https://i.ibb.co/nsDgZN7/cafetera4.png",
//         price: 2500,
//         categoria: "cafeteras",
//     },
//     {
//         id: 15,
//         title: "Cafetera Metalica",
//         stock: 10,
//         photo: "https://i.ibb.co/513qcRm/cafetera5.png",
//         price: 2800,
//         categoria: "cafeteras",
//     },
//     {
//         id: 16,
//         title: "Cafetera Metal Red",
//         stock: 10,
//         photo: "https://i.ibb.co/2NQLqMn/cafetera6.png",
//         price: 5000,
//         categoria: "cafeteras",
//     },
//     {
//         id: 17,
//         title: "Cafetera Milk Red",
//         stock: 10,
//         photo: "https://i.ibb.co/Bjk5qL0/cafetera7.png",
//         price: 7000,
//         categoria: "cafeteras",
//     },
//     {
//         id: 18,
//         title: "Cafetera Doble Black",
//         stock: 10,
//         photo: "https://i.ibb.co/CH0pWLX/cafetera8.webp",
//         price: 4000,
//         categoria: "cafeteras",
//     },
//     {
//         id: 19,
//         title: "Filtro Simple",
//         stock: 10,
//         photo: "https://i.ibb.co/ykM8z7K/filtros2.png",
//         price: 50,
//         categoria: "filtros",
//     },
//     {
//         id: 20,
//         title: "Filtro Doble ",
//         stock: 10,
//         photo: "https://i.ibb.co/5GkVh1Z/filtros3.png",
//         price: 400,
//         categoria: "filtros",
//     },
//     {
//         id: 21,
//         title: "Granos Negros Suaves",
//         stock: 10,
//         photo: "https://i.ibb.co/ZX0fn9M/granos1.png",
//         price: 700,
//         categoria: "granos",
//     },
//     {
//         id: 22,
//         title: "Granos Veganos",
//         stock: 10,
//         photo: "https://i.ibb.co/6stx44K/granos2.png",
//         price: 1400,
//         categoria: "granos",
//     },
//     {
//         id: 23,
//         title: "Granos Stevia",
//         stock: 10,
//         photo: "https://i.ibb.co/0Fn7H9x/granos3.png",
//         price: 900,
//         categoria: "granos",
//     },
//     {
//         id: 24,
//         title: "Granos Colombianos",
//         stock: 10,
//         photo: "https://i.ibb.co/mNMV5gv/granos4.png",
//         price: 2400,
//         categoria: "granos",
//     },
//     {
//         id: 25,
//         title: "Granos Extra Suaves",
//         stock: 10,
//         photo: "https://i.ibb.co/wyCCK9S/granos5.png",
//         price: 1000,
//         categoria: "granos",
//     },
//     {
//         id: 26,
//         title: "Granos Vegetarianos",
//         stock: 10,
//         photo: "https://i.ibb.co/Kx1kr2W/granos6.png",
//         price: 1800,
//         categoria: "granos",
//     },
//     {
//         id: 27,
//         title: "Granos Latte",
//         stock: 10,
//         photo: "https://i.ibb.co/mcsZ4mT/granos7.png",
//         price: 650,
//         categoria: "granos",
//     },
//     {
//         id: 28,
//         title: "Granos Nespresso",
//         stock: 10,
//         photo: "https://i.ibb.co/FhCXVZW/granos8.png",
//         price: 3400,
//         categoria: "granos",
//     },
//     {
//         id: 29,
//         title: "Granos Dolcata",
//         stock: 10,
//         photo: "https://i.ibb.co/bNLPMhR/granos9.png",
//         price: 5400,
//         categoria: "granos",
//     },
//     {
//         id: 30,
//         title: "Taza Infantil",
//         stock: 10,
//         photo: "https://i.ibb.co/bKzc7bC/taza.png",
//         price: 1500,
//         categoria: "tazas",
//     },
//     {
//         id: 31,
//         title: "Taza Red Con Base",
//         stock: 10,
//         photo: "https://i.ibb.co/ZXwmYrn/taza2.png",
//         price: 800,
//         categoria: "tazas",
//     },
//     {
//         id: 32,
//         title: "Taza Mango Rojo Frases",
//         stock: 10,
//         photo: "https://i.ibb.co/MV22phF/taza3.png",
//         price: 1500,
//         categoria: "tazas",
//     },
//     {
//         id: 33,
//         title: "Taza Black Colour",
//         stock: 10,
//         photo: "https://i.ibb.co/RCCDSDf/taza4.png",
//         price: 1100,
//         categoria: "tazas",
//     },
//     {
//         id: 34,
//         title: "Taza Black Frase",
//         stock: 10,
//         photo: "https://i.ibb.co/xF9krYb/taza5.png",
//         price: 800,
//         categoria: "tazas",
//     },
//     {
//         id: 35,
//         title: "Taza Vidrio Small",
//         stock: 10,
//         photo: "https://i.ibb.co/2YcQ8BS/taza6.png",
//         price: 1000,
//         categoria: "tazas",
//     },
//     {
//         id: 36,
//         title: "Taza Red Small",
//         stock: 10,
//         photo: "https://i.ibb.co/4ZcHkf9/taza7.png",
//         price: 900,
//         categoria: "tazas",
//     },
//     {
//         id: 37,
//         title: "Taza Con Base Galletas",
//         stock: 10,
//         photo: "https://i.ibb.co/mRnYsjf/taza8.png",
//         price: 1900,
//         categoria: "tazas",
//     },
//     {
//         id: 38,
//         title: "Taza Con Cuchara",
//         stock: 10,
//         photo: "https://i.ibb.co/vs6kSR7/taza9.png",
//         price: 1500,
//         categoria: "tazas",
//     },
//     {
//         id: 39,
//         title: "Taza Vidrio Medium",
//         stock: 10,
//         photo: "https://i.ibb.co/K0JXtW1/taza10.png",
//         price: 1300,
//         categoria: "tazas",
//     },
//     {
//         id: 40,
//         title: "Taza Vidrio Grande",
//         stock: 10,
//         photo: "https://i.ibb.co/26BSK6d/taza11.png",
//         price: 1300,
//         categoria: "tazas",
//     },
//     {
//         id: 41,
//         title: "Taza Copa",
//         stock: 10,
//         photo: "https://i.ibb.co/FKRcJgr/taza12.png",
//         price: 2000,
//         categoria: "tazas",
//     },
//     {
//         id: 42,
//         title: "Taza Large XXL",
//         stock: 10,
//         photo: "https://i.ibb.co/tqky6vf/taza13.png",
//         price: 2500,
//         categoria: "tazas",
//     },
//     {
//         id: 43,
//         title: "Taza Corazon Red",
//         stock: 10,
//         photo: "https://i.ibb.co/X5ddbfL/taza14.png",
//         price: 2000,
//         categoria: "tazas",
//     },
//     {
//         id: 44,
//         title: "Taza Vidrio Vaso",
//         stock: 10,
//         photo: "https://i.ibb.co/3CTFP5j/taza15.png",
//         price: 1500,
//         categoria: "tazas",
//     },
//     {
//         id: 45,
//         title: "Taza Universo",
//         stock: 10,
//         photo: "https://i.ibb.co/b1HNh2r/taza16.png",
//         price: 1800,
//         categoria: "tazas",
//     },
//     {
//         id: 46,
//         title: "Taza Con Tapa Termica",
//         stock: 10,
//         photo: "https://i.ibb.co/qDw7DJZ/taza17.png",
//         price: 1800,
//         categoria: "tazas",
//     },
//     {
//         id: 47,
//         title: "Taza Basic Colour",
//         stock: 10,
//         photo: "https://i.ibb.co/4j5BBJz/taza18.png",
//         price: 900,
//         categoria: "tazas",
//     },
//     {
//         id: 48,
//         title: "Vaso Termico Red And Black",
//         stock: 10,
//         photo: "https://i.ibb.co/r4TSTnZ/Vaso-Termico.png",
//         price: 2900,
//         categoria: "vasos",
//     },
//     {
//         id: 49,
//         title: "Vaso Termico Personalizado",
//         stock: 10,
//         photo: "https://i.ibb.co/x3CHsgq/Vaso-Termico2.png",
//         price: 1900,
//         categoria: "vasos",
//     },
//     {
//         id: 50,
//         title: "Vaso Termico Metalico",
//         stock: 10,
//         photo: "https://i.ibb.co/yfCYXms/Vaso-Termico3.png",
//         price: 2500,
//         categoria: "vasos",
//     },
//     {
//         id: 51,
//         title: "Vaso Termico Basic Colour",
//         stock: 10,
//         photo: "https://i.ibb.co/nnqTJSS/Vaso-Termico5.png",
//         price: 1400,
//         categoria: "vasos",
//     },
//     {
//         id: 52,
//         title: "Vaso Termico Con Mango Color",
//         stock: 10,
//         photo: "https://i.ibb.co/ygfRqc4/Vaso-Termico6.png",
//         price: 1700,
//         categoria: "vasos",
//     },
//     {
//         id: 53,
//         title: "Vaso Termico Metalico Color",
//         stock: 10,
//         photo: "https://i.ibb.co/NVfHjQ2/Vaso-Termico7.png",
//         price: 2200,
//         categoria: "vasos",
//     },
//     {
//         id: 54,
//         title: "Vaso Termico Small Personalizado",
//         stock: 10,
//         photo: "https://i.ibb.co/qrk6qXb/Vaso-Termico8.png",
//         price: 1000,
//         categoria: "vasos",
//     },
//     {
//         id: 55,
//         title: "Vaso Termico Stanley",
//         stock: 10,
//         photo: "https://i.ibb.co/ZT4GLgT/Vaso-Termico4.png",
//         price: 5900,
//         categoria: "vasos",
//     },
// ];

// export const getFetch = new Promise((resolve, reject) => {
//     setTimeout(() => {
//         resolve(products);
//     }, 2000);
// });
